# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.db.models.deletion
import uuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackAdmin',
            fields=[
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('account', models.CharField(unique=True, max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('email', models.EmailField(unique=True, max_length=75)),
                ('user_name', models.CharField(max_length=45)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_admin', models.CharField(max_length=45)),
                ('update_admin', models.CharField(max_length=45)),
                ('deactivated_admin', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Back_Admin',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BonusRecord',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('serial', models.CharField(max_length=255)),
                ('used_date', models.DateTimeField(null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Bonus_Record',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BonusType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type_name', models.CharField(max_length=45)),
                ('item', models.FloatField(default=0.0)),
                ('send_organization', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('content', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Bonus_Type',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('card_number', models.CharField(max_length=16)),
                ('security_code', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'Card_Payment',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CompulsoryInsurance',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('photo_url', models.ImageField(upload_to=b'upload/compulsory_insurance_photo/')),
                ('valid_begin_date', models.DateTimeField()),
                ('valid_end_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Compulsory_Insurance',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreditCardType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type_name', models.CharField(max_length=45)),
                ('security_code_length', models.IntegerField()),
                ('card_length', models.IntegerField()),
                ('card_begin_number', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_admin', models.CharField(max_length=45)),
                ('update_admin', models.CharField(max_length=45)),
                ('deactivated_admin', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Credit_Card_Type',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('photo_url', models.ImageField(upload_to=b'upload/user_profile_photo/')),
                ('identification_number', models.CharField(max_length=10)),
                ('birth_year', models.IntegerField(default=None, max_length=4)),
                ('birth_month', models.IntegerField(default=None, max_length=2)),
                ('birth_day', models.IntegerField(default=None, max_length=2)),
                ('gender', models.BooleanField(default=None)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Driver_Info',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DrivingLicenseCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type_name', models.CharField(max_length=45)),
                ('business', models.BooleanField(default=False)),
                ('LargeTrucks', models.BooleanField(default=None)),
                ('Trailer', models.BooleanField(default=None)),
                ('Bus', models.BooleanField(default=None)),
                ('Van', models.BooleanField(default=None)),
                ('LargeHeavyMotorcycle', models.BooleanField(default=None)),
                ('OriginalHeavyMotorcycle', models.BooleanField(default=None)),
                ('LightMotorcycle', models.BooleanField(default=None)),
                ('SmallLightMotorcycle', models.BooleanField(default=None)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_admin', models.CharField(max_length=45)),
                ('update_admin', models.CharField(max_length=45)),
                ('deactivated_admin', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Driving_Licnese_Category',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DrivingLicnese',
            fields=[
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('publish_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
                ('fk_driver', models.ForeignKey(related_name='lincenses', to='web.DriverInfo')),
                ('fk_license_category', models.ForeignKey(related_name='licenses', on_delete=django.db.models.deletion.SET_NULL, to='web.DrivingLicenseCategory', null=True)),
            ],
            options={
                'db_table': 'Driving_Licnese',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FacebookAccount',
            fields=[
                ('uid', models.BigIntegerField(serialize=False, primary_key=True, db_column=b'UID')),
                ('token', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Facebook_Account',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=45)),
                ('photo_url', models.ImageField(upload_to=b'upload/group_profile_photo/')),
                ('address', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Group_Info',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='IndustryCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type_name', models.CharField(max_length=45)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_admin', models.CharField(max_length=45)),
                ('update_admin', models.CharField(max_length=45)),
                ('deactivated_admin', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Industry_Category',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('account', models.CharField(unique=True, max_length=45)),
                ('email', models.EmailField(unique=True, max_length=75)),
                ('password', models.CharField(max_length=45)),
                ('cell_phone', models.CharField(max_length=11)),
                ('phone_sms_verification', models.BooleanField(default=False)),
                ('activation_key', uuidfield.fields.UUIDField(unique=True, max_length=32, editable=False, blank=True)),
                ('key_expired', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Memebr_Account',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MemebrType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type_name', models.CharField(max_length=45)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_admin', models.CharField(max_length=45)),
                ('update_admin', models.CharField(max_length=45)),
                ('deactivated_admin', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Member_Type',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('departure', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('wage', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Order',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('description', models.CharField(max_length=255)),
                ('item_motor', models.IntegerField(default=0)),
                ('item_pet', models.IntegerField(default=0)),
                ('item_single_bed', models.IntegerField(default=0)),
                ('item_twin_bed', models.IntegerField(default=0)),
                ('item_bookcase', models.IntegerField(default=0)),
                ('item_cupboard', models.IntegerField(default=0)),
                ('item_table', models.IntegerField(default=0)),
                ('item_chair', models.IntegerField(default=0)),
                ('item_refrigerator', models.IntegerField(default=0)),
                ('item_sofa', models.IntegerField(default=0)),
                ('item_fragile', models.IntegerField(default=0)),
                ('item_Other', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Order_Detail',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('state', models.CharField(max_length=45)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_admin', models.CharField(max_length=45)),
                ('update_admin', models.CharField(max_length=45)),
                ('deactivated_admin', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Order_Status',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=45)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_admin', models.CharField(max_length=45)),
                ('update_admin', models.CharField(max_length=45)),
                ('deactivated_admin', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Payment_Option',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PaymentRecords',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
                ('fk_group_info', models.ForeignKey(related_name='payment_records', on_delete=django.db.models.deletion.SET_NULL, to='web.GroupInfo', null=True)),
                ('fk_payment_option', models.ForeignKey(related_name='payment_records', to='web.PaymentOption')),
            ],
            options={
                'db_table': 'Payment_Records',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PoliceClearance',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('photo_url', models.ImageField(upload_to=b'upload/police_clearance_photo/')),
                ('valid_begin_date', models.DateTimeField()),
                ('valid_end_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Police_Clearance',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=45)),
                ('photo_url', models.ImageField(upload_to=b'upload/user_profile_photo/')),
                ('birth_year', models.IntegerField(default=None, max_length=4)),
                ('birth_month', models.IntegerField(default=None, max_length=2)),
                ('birth_day', models.IntegerField(default=None, max_length=2)),
                ('gender', models.BooleanField(default=None)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
                ('fk_account', models.OneToOneField(to='web.MemberAccount')),
                ('fk_fb_account', models.OneToOneField(to='web.FacebookAccount')),
            ],
            options={
                'db_table': 'User_Info',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('accessories', models.CharField(max_length=255, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Vehicle',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VehicleAccessories',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('accessories_name', models.CharField(max_length=45)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_admin', models.CharField(max_length=45)),
                ('update_admin', models.CharField(max_length=45)),
                ('deactivated_admin', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Vehicle_Accessories',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VehicleBand',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('band_name', models.CharField(max_length=45)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_admin', models.CharField(max_length=45)),
                ('update_admin', models.CharField(max_length=45)),
                ('deactivated_admin', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Vehicle_Band',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VehicleBandModel',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('model_name', models.CharField(max_length=45)),
                ('weight', models.IntegerField()),
                ('displacement_lower', models.IntegerField()),
                ('displacement_upper', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_admin', models.CharField(max_length=45)),
                ('update_admin', models.CharField(max_length=45)),
                ('deactivated_admin', models.CharField(max_length=45, null=True, blank=True)),
                ('fk_vehicle_band', models.ForeignKey(related_name='vehicle_models', to='web.VehicleBand')),
            ],
            options={
                'db_table': 'Vehicle_Band_Model',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type_name', models.CharField(max_length=45)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_admin', models.CharField(max_length=45)),
                ('update_admin', models.CharField(max_length=45)),
                ('deactivated_admin', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Vehicle_Category',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VehicleLicense',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('photo_url', models.ImageField(upload_to=b'upload/vehicle_license_photo/')),
                ('valid_begin_date', models.DateTimeField()),
                ('valid_end_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Vehicle_License',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VehiclePlate',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('number', models.CharField(max_length=255)),
                ('photo_url', models.ImageField(upload_to=b'upload/vehicle_plate_photo/')),
                ('valid_begin_date', models.DateTimeField()),
                ('valid_end_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Vehicle_Plate',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VocationCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type_name', models.CharField(max_length=45)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_admin', models.CharField(max_length=45)),
                ('update_admin', models.CharField(max_length=45)),
                ('deactivated_admin', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Vocation_Category',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='vehiclebandmodel',
            name='fk_vehicle_type',
            field=models.ForeignKey(related_name='vehicle_models', on_delete=django.db.models.deletion.SET_NULL, to='web.VehicleCategory', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fk_band_model',
            field=models.ForeignKey(related_name='vehicles', on_delete=django.db.models.deletion.SET_NULL, to='web.VehicleBandModel', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fk_compulsory_insurance',
            field=models.ForeignKey(related_name='vehicles', on_delete=django.db.models.deletion.SET_NULL, to='web.CompulsoryInsurance', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fk_driver',
            field=models.ForeignKey(related_name='vehicles', to='web.DriverInfo'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fk_driving_license',
            field=models.ForeignKey(related_name='vehicles', on_delete=django.db.models.deletion.SET_NULL, to='web.DrivingLicnese', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fk_police_clearance',
            field=models.ForeignKey(related_name='vehicles', on_delete=django.db.models.deletion.SET_NULL, to='web.PoliceClearance', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fk_vehicle_license',
            field=models.ForeignKey(related_name='vehicles', on_delete=django.db.models.deletion.SET_NULL, to='web.VehicleLicense', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fk_vehicle_plate',
            field=models.ForeignKey(related_name='vehicles', to='web.VehiclePlate'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='fk_vocation_type',
            field=models.ForeignKey(related_name='users', on_delete=django.db.models.deletion.SET_NULL, to='web.VocationCategory', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='paymentrecords',
            name='fk_user_info',
            field=models.ForeignKey(related_name='payment_records', on_delete=django.db.models.deletion.SET_NULL, to='web.UserInfo', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='order',
            name='fk_detail',
            field=models.OneToOneField(to='web.OrderDetail'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='order',
            name='fk_driver',
            field=models.ForeignKey(related_name='orders', to='web.DriverInfo'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='order',
            name='fk_group_info',
            field=models.ForeignKey(related_name='orders', on_delete=django.db.models.deletion.SET_NULL, to='web.GroupInfo', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='order',
            name='fk_payment_record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.PaymentRecords'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='order',
            name='fk_state',
            field=models.ForeignKey(related_name='orders', to='web.OrderState'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='order',
            name='fk_user_info',
            field=models.ForeignKey(related_name='orders', on_delete=django.db.models.deletion.SET_NULL, to='web.UserInfo', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='memberaccount',
            name='fk_member_type',
            field=models.ForeignKey(related_name='type_accounts', on_delete=django.db.models.deletion.SET_NULL, to='web.MemebrType', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='fk_account',
            field=models.OneToOneField(to='web.MemberAccount'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='fk_industry',
            field=models.ForeignKey(related_name='groups', on_delete=django.db.models.deletion.SET_NULL, to='web.IndustryCategory', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='driverinfo',
            name='fk_account',
            field=models.OneToOneField(to='web.MemberAccount'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='driverinfo',
            name='fk_fb_account',
            field=models.OneToOneField(to='web.FacebookAccount'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='driverinfo',
            name='fk_vocation_type',
            field=models.ForeignKey(related_name='drivers', on_delete=django.db.models.deletion.SET_NULL, to='web.VocationCategory', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='fk_card_type',
            field=models.ForeignKey(related_name='card_payments', on_delete=django.db.models.deletion.SET_NULL, to='web.CreditCardType', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='fk_payment_record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.PaymentRecords'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bonusrecord',
            name='fk_bonus_type',
            field=models.ForeignKey(related_name='bonus', to='web.BonusType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bonusrecord',
            name='fk_group_info',
            field=models.ForeignKey(related_name='bonus_records', on_delete=django.db.models.deletion.SET_NULL, to='web.GroupInfo', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bonusrecord',
            name='fk_user_info',
            field=models.ForeignKey(related_name='bonus_records', on_delete=django.db.models.deletion.SET_NULL, to='web.UserInfo', null=True),
            preserve_default=True,
        ),
    ]
