# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompulsoryInsurance',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('photo_url', models.ImageField(upload_to=b'upload/compulsory_insurance_photo/')),
                ('valid_begin_date', models.DateTimeField()),
                ('valid_end_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Compulsory_Insurance',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DrivingLicenseCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type_name', models.CharField(max_length=45)),
                ('business', models.BooleanField(default=False)),
                ('LargeTrucks', models.BooleanField(default=None)),
                ('Trailer', models.BooleanField(default=None)),
                ('Bus', models.BooleanField(default=None)),
                ('Van', models.BooleanField(default=None)),
                ('LargeHeavyMotorcycle', models.BooleanField(default=None)),
                ('OriginalHeavyMotorcycle', models.BooleanField(default=None)),
                ('LightMotorcycle', models.BooleanField(default=None)),
                ('SmallLightMotorcycle', models.BooleanField(default=None)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_admin', models.CharField(max_length=45)),
                ('update_admin', models.CharField(max_length=45)),
                ('deactivated_admin', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Driving_Licnese_Category',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DrivingLicnese',
            fields=[
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('publish_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
                ('fk_driver', models.ForeignKey(related_name='lincenses', to='member.DriverInfo')),
                ('fk_license_category', models.ForeignKey(related_name='licenses', on_delete=django.db.models.deletion.SET_NULL, to='vehicle.DrivingLicenseCategory', null=True)),
            ],
            options={
                'db_table': 'Driving_Licnese',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PoliceClearance',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('photo_url', models.ImageField(upload_to=b'upload/police_clearance_photo/')),
                ('valid_begin_date', models.DateTimeField()),
                ('valid_end_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Police_Clearance',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('accessories', models.CharField(max_length=255, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Vehicle',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VehicleAccessories',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('accessories_name', models.CharField(max_length=45)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_admin', models.CharField(max_length=45)),
                ('update_admin', models.CharField(max_length=45)),
                ('deactivated_admin', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Vehicle_Accessories',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VehicleBand',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('band_name', models.CharField(max_length=45)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_admin', models.CharField(max_length=45)),
                ('update_admin', models.CharField(max_length=45)),
                ('deactivated_admin', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Vehicle_Band',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VehicleBandModel',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('model_name', models.CharField(max_length=45)),
                ('weight', models.IntegerField()),
                ('displacement_lower', models.IntegerField()),
                ('displacement_upper', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_admin', models.CharField(max_length=45)),
                ('update_admin', models.CharField(max_length=45)),
                ('deactivated_admin', models.CharField(max_length=45, null=True, blank=True)),
                ('fk_vehicle_band', models.ForeignKey(related_name='vehicle_models', to='vehicle.VehicleBand')),
            ],
            options={
                'db_table': 'Vehicle_Band_Model',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type_name', models.CharField(max_length=45)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_admin', models.CharField(max_length=45)),
                ('update_admin', models.CharField(max_length=45)),
                ('deactivated_admin', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Vehicle_Category',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VehicleLicense',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('photo_url', models.ImageField(upload_to=b'upload/vehicle_license_photo/')),
                ('valid_begin_date', models.DateTimeField()),
                ('valid_end_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Vehicle_License',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VehiclePlate',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('number', models.CharField(max_length=255)),
                ('photo_url', models.ImageField(upload_to=b'upload/vehicle_plate_photo/')),
                ('valid_begin_date', models.DateTimeField()),
                ('valid_end_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True, blank=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('create_account', models.CharField(max_length=45)),
                ('update_account', models.CharField(max_length=45)),
                ('deactivated_account', models.CharField(max_length=45, null=True, blank=True)),
            ],
            options={
                'db_table': 'Vehicle_Plate',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='vehiclebandmodel',
            name='fk_vehicle_type',
            field=models.ForeignKey(related_name='vehicle_models', on_delete=django.db.models.deletion.SET_NULL, to='vehicle.VehicleCategory', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fk_band_model',
            field=models.ForeignKey(related_name='vehicles', on_delete=django.db.models.deletion.SET_NULL, to='vehicle.VehicleBandModel', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fk_compulsory_insurance',
            field=models.ForeignKey(related_name='vehicles', on_delete=django.db.models.deletion.SET_NULL, to='vehicle.CompulsoryInsurance', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fk_driver',
            field=models.ForeignKey(related_name='vehicles', to='member.DriverInfo'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fk_driving_license',
            field=models.ForeignKey(related_name='vehicles', on_delete=django.db.models.deletion.SET_NULL, to='vehicle.DrivingLicnese', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fk_police_clearance',
            field=models.ForeignKey(related_name='vehicles', on_delete=django.db.models.deletion.SET_NULL, to='vehicle.PoliceClearance', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fk_vehicle_license',
            field=models.ForeignKey(related_name='vehicles', on_delete=django.db.models.deletion.SET_NULL, to='vehicle.VehicleLicense', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fk_vehicle_plate',
            field=models.ForeignKey(related_name='vehicles', to='vehicle.VehiclePlate'),
            preserve_default=True,
        ),
    ]
